[project]
name = "langchain-web-search-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "langchain>=1.2.6",
    "langchain-groq>=1.1.1",
    "streamlit>=1.53.0",
]
